### ISSUE TITLE
Annotation of athenaeum-f68-s1

### ISSUE THREAD

**Issue by nikitakit** [UniversalDependencies/UD_German-LIT#2]
I have a question about whether the annotation of `athenaeum-f68-s1` is correct.

> Nur der Kunstliebhaber liebt wirklich die Kunst, der auf einige seiner Wünsche völlig Verzicht tun kann, wo er andre ganz befriedigt findet, der auch das Liebste noch streng würdigen mag, der sich im Notfall Erklärungen gefallen läßt, und Sinn für Kunstgeschichte hat.

<img width="1218" alt="athenaeum-f68-s1" src="https://github.com/UniversalDependencies/UD_German-LIT/assets/252225/fa284248-d6db-458d-96b0-0d51a1e247aa">

The main concern is that all three of _Kunstliebhaber_/_liebt_/_Kunst_ serve as attachment points for the later clauses. 

Unfortunately I don't know enough German to tell if this is correct, but translating this sentence suggests otherwise. I came across it because my scripts flagged it as having a highly non-projective structure beyond what is typical cross-linguistically.

**Comment by dan-zeman** [comment]
Fixed in dev. Thanks for reporting!
