### ISSUE TITLE
adjectives tagged as VERB/VVINF

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/UD_German-LIT#3]
I've just found a view adjectives which have UPOS `VERB` (even though that not forms of verbs and use the deprel `amod`. I checked the context, and I think this is an error. Here is the output of `grep -n  VERB.*amod UD_German-LIT/de_lit-ud-test.conllu` (without two lines where the adjective is indeed a past participle used as adjective:

```
10611:13	eignen	eignen	VERB	VVFIN	_	14	amod	_	_
20918:2 	schöne	schön	VERB	VVFIN	_	7	amod	_	SpaceAfter=No
32334:10	witzigen	witzig	VERB	VVFIN	_	11	amod	_	_
34463:17	engern	engern	VERB	VVINF	_	20	amod	_	_
38973:16	schönen	schön	VERB	VVFIN	_	21	amod	_	SpaceAfter=No
42572:18	schamhaften	schamhaft	VERB	VVFIN	_	22	amod	_	SpaceAfter=No
42574:20	schüchtern	schüchtern	VERB	VVINF	_	18	amod	_	_
44469:5 	weitern	weitern	VERB	VVINF	_	6	amod	_	_
```

**Comment by gossebouma** [comment]
I agree with the fact that these are not VERB, but I am surprised that the German treebanks in general do not seem to mark participles that are used as amod as VERB. For instance, UD_German-LIT has cases like _ausgemachte_ in _eine ausgemachte Sache_ as amod/ADJ, where this looks like a past particple that is used as adjective (also, the lemma is _ausgemacht_, where _ausmachen_ would be the verbal lemma). 

The Dutch treebanks mark comparable cases as amod/VERB and assign the verbal lemma. 

I think I prefer the Dutch solution, esp the fact that the lemma is the verbal lemma, and not the uninflected particple form.

**Comment by jheinecke** [comment]
I agree totally, I'd prefer amod/VERB plus verbal lemma as well. In fact this is a point I wanted to raise in the general UD issues, since at least in Romance languages many, if not all past participles which are used as adjectives are ADJ/amod and the lemma is the past participle, however if there is an ADV attached to the participle we can find both ADJ/amod + adj.lemma and VERB/amod + verbal lemma...
I wonder whether ther could be a common solution for at least those languages which have something similar to participles (Romance, Germanic, Slavic to a certain extend within the IE languages)

**Comment by dan-zeman** [comment]
I fixed the non-participial adjectives mentioned above – thanks for reporting them!

I am closing the issue now, as the rest is a general guidelines discussion (feel free to open an issue in the docs repository if further discussion is needed). I just note that I think you should use `acl` instead of `amod` if you use the `VERB` tag for a participle. Conversely, `ADJ` typically means `amod` whether or not participial (although it can be `acl` too, especially if a copula is used).
